### PR TITLE
20241105 Fix bugs + enhancements

### LINKED ISSUE #264: Enhancement: Update deadline parsing check
Currently only throws a simple error that string provided is in invalid format.

Enhance the check such that it informs users of where the date was incorrectly inputted.

### LINKED ISSUE #266: Bug: Tags should be case-insenstive when adding
I am able to add `t/T1` and `t/t1` successfully

image

### LINKED ISSUE #268: Bug: `CS2103-F1-9` and `CS2103-F1-09` should be considered the same group
image

### PR DESCRIPTION
**Pull request by ghos7ie**
closes #264 - update deadline error message
closes #268 - improve GroupName parsing
closes #266 - make tags case-insensitive

### CODE REVIEW

File: src/main/java/seedu/address/model/group/GroupName.java [hunk 1]
```diff
@@ -20,7 +23,8 @@ public class GroupName {
      * The first character of the address must not be a whitespace,
      * otherwise " " (a blank string) becomes a valid input.
      */
-    public static final String VALIDATION_REGEX = "^(?i)CS2103T?-[A-Z]\\d+-\\d+$";
+    public static final String VALIDATION_REGEX = "^(?i)(?<coursepart>CS2103T?)-(?<tutorialpart>[A-Z]\\d+)-"
```
Comment (dez2003) [inline src/main/java/seedu/address/model/group/GroupName.java:26]: Just to confirm, the validation regex is still the same, but when formatting the group name it removes any leading 0s?

File: src/main/java/seedu/address/model/tag/Tag.java [hunk 2]
```diff
@@ -53,7 +53,7 @@ public boolean equals(Object other) {
 
     @Override
     public int hashCode() {
-        return tagName.hashCode();
+        return tagName.toLowerCase().hashCode();
```
Comment (dez2003) [inline src/main/java/seedu/address/model/tag/Tag.java:56]: So does this mean there can't be duplicate tags for a student?

**Review by dez2003 — APPROVED** [review]
Looks good!

File: src/main/java/seedu/address/model/group/GroupName.java (hunk 1 above)
Comment (ghos7ie) [reply src/main/java/seedu/address/model/group/GroupName.java:26]: yep, the regex is the same.

i just added the capture groups for easy stripping

File: src/main/java/seedu/address/model/tag/Tag.java (hunk 2 above)
Comment (ghos7ie) [reply src/main/java/seedu/address/model/tag/Tag.java:56]: yes, see #266 

semantically `t1` and `T1` are the same thing so there is no reason for them to be treated differently.

the additional `.toLowerCase()` in the hash is because hashset uses both equals() and hashCode to check if the provided elements are the same

putting it here will preserve the provided value of the tag
