### PR TITLE
Updates on the following features and bugs

### LINKED ISSUE #191: Bug: Add_Group Message_Usage missing a new line
image

Parameters should be on a newline.

### LINKED ISSUE #196: Code Quality: `LIST_X_MARKER` should all be declared in a separate class and reused
Currently all commands declare them separately, but the variables should be declared in one location

### LINKED ISSUE #206: Enhancement: Add an existing task to a group
`aetg i/[Task_Index] gn/[Group_Name]...`

### LINKED ISSUE #207: Enhancement: Add task to multiple groups
Current: `atg gn/[Group_Name] tn/[Task Name] td/[Task Deadline]`

Enhancement: `atg gn/[Group_Name]... tn/[Task Name] td/[Task Deadline]`

### LINKED ISSUE #225: Bug: Edit Task All - missing newline in MESSAGE_USAGE
image
Parameters should be on a newline

### LINKED ISSUE #226: Nitpick: AddTaskToAll Command update to "add_task" since AddTaskToGroup already has "add_task_grp"

### PR DESCRIPTION
**Pull request by ghos7ie**
- Change `add_task_all` to `add_task` (closes #226)
- Add missing newline in EditTaskAll (closes #225)
- Enhance Add Task to Group to accept multiple groups (closes #207)
- Added new feature -> Add existing task to groups (closes #206)
- Consolidate List Markers (closes #196)
- Add missing newline in AddGroup (closes #191)

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java [hunk 1]
```diff
@@ -32,58 +35,64 @@ public class AddTaskToGroupCommand extends Command {
...
-        if (model.hasTaskInGroup(task, group)) {
-            throw new CommandException(MESSAGE_DUPLICATE_TASK_IN_GROUP);
-        }
-
-        model.addTaskToGroup(task, group);
-        if (!model.hasTask(task)) {
-            model.addTask(task);
-        } else {
-            model.increaseGroupWithTask(task);
+        List<GroupName> groups = toAddInto.stream().toList();
```
Comment (SooYap) [inline src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java:70]: Since you've added in the add existing task to group function is it better if we raise an exception if a user adds an existing task using this function?

File: src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java [hunk 2]
```diff
@@ -32,58 +35,64 @@ public class AddTaskToGroupCommand extends Command {
...
+                model.addTask(task);
+            } else {
+                model.increaseGroupWithTask(task);
+            }
+            groupsAdded.append(groupName).append("\n");
         }
-        model.setMostRecentGroupTaskDisplay(group.getGroupName().fullName);
-        model.updateFilteredGroupList(x -> x.getGroupName().equals(group.getGroupName()));
+        model.setMostRecentGroupTaskDisplay(groups.get(lastIndex).getGroupName());
+        model.updateFilteredGroupList(x -> x.getGroupName().equals(groups.get(lastIndex)));
```
Comment (SooYap) [inline src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java:92]: Is it better to adjust the predicate so that either we display:

Task List Panel showing the task that has been added
or
Group List Panel showing all the groups that have this task being added in.

File: src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java (hunk 1 above)
Comment (ghos7ie) [reply src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java:70]: Do you mean here in AddTaskToGroup or AddExistingTaskToGroup?

I did miss out checking whether the task exists globally already though, will add that in

File: src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java (hunk 2 above)
Comment (ghos7ie) [reply src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java:92]: ya, I was thinking if we can update display all tasks UI to show the groups, we should direct the user there after this command

but I followed the previous behaviour for this currently

File: src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java (hunk 1 above)
Comment (ghos7ie) [reply src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java:70]: wait actually does `model.increaseGroupWithTask` handle incrementing the counter if the task exists globally?

Comment (SooYap) [reply src/main/java/seedu/address/logic/commands/addcommands/AddTaskToGroupCommand.java:70]: I meant like if the task exists globally then if the user tries to add a task using this function, with the same task name and deadline as a task in the global list then we should disallow it because there's another function for it.

And yeah the increaseGroupWithTask function does increment the counter of the global task. The groupsWithTask parameter for a Task in a group does not matter. Because its function is to signal when a task is to be deleted from the global list.

**Comment by ghos7ie** [comment]
Closes #231
Closes #230

**Review by SooYap — APPROVED** [review]
lgtm!!
